### PR TITLE
VAddNode can now return LicenseLimitError

### PR DESCRIPTION
**Pull request by jizhuoyu**
This change is specific to vclusterops deployment. It will recognize rfc error type `"https://integrators.vertica.com/rest/errors/license-issue"` returned from HTTPS endpoint while adding a node. The operator now treats this like admintools deployments and writes a clear event log message.

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Can you include the event message? Also, I think we can re-enable the restart-node-multi-sc in vcluster mode. Can you try that out and if it works move it to e2e-leg-2?

**Comment by jizhuoyu** [comment]
> Can you include the event message? Also, I think we can re-enable the restart-node-multi-sc in vcluster mode. Can you try that out and if it works move it to e2e-leg-2?


event message:
```
> k get events
LAST SEEN   TYPE      REASON               OBJECT        MESSAGE
19s         Warning   Unhealthy            pod/v-sc1-3   Startup probe failed: vsql: could not connect to server: Connection refused...
11m         Normal    AddNodeStart         verticadb/v   Starting add database node for pod(s) 'v-sc1-3'
11m         Warning   AddNodeLicenseFail   verticadb/v   License issue: Cannot create another node. The current license permits 3 node(s) and the database catalog already contains 3 node(s)
```

**Comment by jizhuoyu** [comment]
> Can you include the event message? Also, I think we can re-enable the restart-node-multi-sc in vcluster mode. Can you try that out and if it works move it to e2e-leg-2?

and operator log as well
[add_node_fail_new.log](https://github.com/vertica/vertica-kubernetes/files/13169245/add_node_fail_new.log)

**Comment by jizhuoyu** [comment]
Just merged with the latest main branch to fix e2e test failure

**Review by spilchen — APPROVED** [review]

**Pull request merged**
