### PR TITLE
Fix bug that prevented subcluster names with hyphens

### PR DESCRIPTION
**Pull request by spilchen**
This is a bug fix for when the subcluster name in the CR includes hyphens.  There are a couple of cases where we need to update the default subcluster in Vertica.  The SQL we generated for these commands didn't have quotes around the name, so they were failing.  Failure to change the default cluster prevented removal subcluster in some cases and messed up the assignment of nodes to subclusters when creating the database.

Updated the multi-sc testcase (now renamed to multi-sc-sanity) to expose the issue that the bug fix resolves.

### CODE REVIEW

**Review by roypaulin — APPROVED** [review]
Looks good. Are you going to add the changie for my PR that was closed yesterday on this PR?

**Review by roypaulin — COMMENTED** [review]
Looks like there are some conflicts. I hope they won't be difficult to resolve.

**Comment by spilchen** [comment]
Thanks for the heads up about the conflicts.  It was the copyright year that I changed, so it was an easy resolution.

**Comment by spilchen** [comment]
> Are you going to add the changie for my PR that was closed yesterday on this PR?

I added the changie in the big copyright year PR I had.

**Pull request merged**
