### PR TITLE
Set the JAVA_HOME environment variable in the Vertica v2 container

### PR DESCRIPTION
**Pull request by jizhuoyu**
Add ENV instruction in v2 vertica image Dockerfile to make JAVA_HOME env var available in all server containers

### CODE REVIEW

**Comment by jizhuoyu** [comment]
Do we also want to remove these lines from Dockerfile?
```
  && if [[ ${MINIMAL^^} != "YES" ]] ; then \
    echo "JAVA_HOME=/usr" >> /etc/environment; \
  fi \
```

**Comment by jizhuoyu** [comment]
Do we want to make the same changes to v1 image Dockerfile as well?

**Comment by spilchen** [comment]
> Do we also want to remove these lines from Dockerfile?
> 
> ```
>   && if [[ ${MINIMAL^^} != "YES" ]] ; then \
>     echo "JAVA_HOME=/usr" >> /etc/environment; \
>   fi \
> ```

Yes, lets remove this part from the v2 image.

**Comment by spilchen** [comment]
> Do we want to make the same changes to v1 image Dockerfile as well?

No. Let's keep the v1 image the same. We know the JAVA_HOME fix there works. This change should be targeted only for vclusterops deployments.

**Comment by roypaulin** [comment]
We should move udx-java to e2e-udx for testing. Matt are you going to build a v2 image?

**Comment by spilchen** [comment]
We could also do the udx-java changes as a follow-up. Once these changes are pushed to main the jenkins pipeline nightly run will rebuild the v2 image. So, we can do the follow-up after that is done.

**Review by spilchen — APPROVED** [review]

**Review by roypaulin — APPROVED** [review]

**Pull request merged**
