### PR TITLE
Duane/add dblink

### PR DESCRIPTION
**Pull request by NerdLogic**
This installs dblink on the image, but doesn't load it into vertica.

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
This will break the nightly build, and I don't see an easy way to fix this. The nightly build runs against the latest server version, which is not yet released. However, this adds a new dependency that we pull a released dblink from the dblink repo. But, we can never fulfill this dependency because we are using an unreleased version of the server.

**Comment by NerdLogic** [comment]
> This will break the nightly build, and I don't see an easy way to fix this. The nightly build runs against the latest server version, which is not yet released. However, this adds a new dependency that we pull a released dblink from the dblink repo. But, we can never fulfill this dependency because we are using an unreleased version of the server.

Yes.  Don't merge this until we have the UDX container build and the DBLink build automated and a mechanism to upload ldblink.so in the same way that the rpm is uploaded.  There are JIRAs for that effort already.  I didn't want to lose track of these changes, so I created a PR.

Optionally, we could just add the unixodbc package and that already saves the customer from needing to create their own image.  They would just need to manually download the correct ldblink.so and install it on a running k8s container just like they would for any other udx.  Well, they would also need to configure their odbc settings on each k8s container which is something we can't really package for them.

**Comment by spilchen** [comment]
I kind of like your idea of just adding the unixodbc package. Otherwise, this PR may sit around a while waiting for dblink automation to happen.

**Comment by spilchen** [comment]
Closing for now. We can pick these changes up again in the future.

**Pull request closed without merging**
